[build-system]
requires = [
    "setuptools>=66",
    "wheel",
    "ninja",
    "cmake>=3.12"
]
build-backend = "setuptools.build_meta"

[project]
name = "MoleKing"
version = "1.6.0"
description = "MoleKing is a python module for chemists aiming to add common principles to python. This module adds new types of python variables, MoleKing_Molecule; MoleKing_Atom; MoleKing_SupraMolecule, and MoleKing_Output, alongside many features considered common knowledge among chemists."
requires-python = ">=3.8"

[project.optional-dependencies]
test = ["pytest>=6.0"]


[tool.mypy]
files = "setup.py"
python_version = "3.7"
strict = true
show_error_codes = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true

[[tool.mypy.overrides]]
module = ["ninja"]
ignore_missing_imports = true

[tool.setuptools.packages.find]
where = ["."]
include = ["MoleKing"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["tests"]

[tool.cibuildwheel.linux]
test-command = "pytest {project}/tests"
test-extras = ["test"]
before-build = "rm -rf {project}/build"

[tool.cibuildwheel.windows]
test-command = "pytest {project}/tests"
test-extras = ["test"]

[tool.cibuildwheel.macos]
test-command = "pytest {project}/tests"
test-extras = ["test"]

[tool.ruff]
extend-select = [
  "B",    # flake8-bugbear
  "B904",
  "I",    # isort
  "PGH",  # pygrep-hooks
  "RUF",  # Ruff-specific
  "UP",   # pyupgrade
]
extend-ignore = [
  "E501",   # Line too long
]
target-version = "py37"